# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coolerator.vision}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Innis"]
  s.date = %q{2009-11-16}
  s.description = %q{A Rails plugin}
  s.email = %q{corey@coolerator.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     ".screwrc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/placeholder.txt",
     "app/placeholder.txt",
     "coolerator.vision.gemspec",
     "lib/coolerator.vision.rb",
     "public/javascripts/vendor/coolerator/coolerator.base.js",
     "public/javascripts/vendor/coolerator/coolerator.base.js",
     "public/javascripts/vendor/coolerator/coolerator.filter.js",
     "public/javascripts/vendor/coolerator/coolerator.filter.js",
     "public/javascripts/vendor/coolerator/coolerator.module.js",
     "public/javascripts/vendor/coolerator/coolerator.module.js",
     "public/javascripts/vendor/coolerator/coolerator.registrar.js",
     "public/javascripts/vendor/coolerator/coolerator.registrar.js",
     "public/javascripts/vendor/coolerator/coolerator.remote.js",
     "public/javascripts/vendor/coolerator/coolerator.remote.js",
     "public/javascripts/vendor/coolerator/coolerator.view.js",
     "public/javascripts/vendor/coolerator/coolerator.view.js",
     "public/javascripts/vendor/jquery/jquery.easing.js",
     "public/javascripts/vendor/jquery/jquery.easing.js",
     "public/javascripts/vendor/jquery/jquery.js",
     "public/javascripts/vendor/jquery/jquery.js",
     "public/javascripts/vendor/prez/prez.js",
     "public/javascripts/vendor/prez/prez.js",
     "rails/init.rb",
     "script/pair",
     "spec/coolerator.vision_spec.rb",
     "spec/javascripts/support/spec_helper.js",
     "spec/javascripts/vendor/coolerator/coolerator.base_spec.js",
     "spec/javascripts/vendor/coolerator/coolerator.filter_spec.js",
     "spec/javascripts/vendor/coolerator/coolerator.module_spec.js",
     "spec/javascripts/vendor/coolerator/coolerator.registrar_spec.js",
     "spec/javascripts/vendor/coolerator/coolerator.remote_spec.js",
     "spec/javascripts/vendor/coolerator/coolerator.view_spec.js",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/coreyti/coolerator.vision}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails plugin}
  s.test_files = [
    "spec/coolerator.vision_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/array_extension.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/asset_location.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/asset_manager.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/configuration.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/dispatcher.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/js_file.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/dir.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/file.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/file_not_found.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/root.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/spec_dir.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/spec_runner.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/streaming_spec_runner.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources/suite_completion.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/resources.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/server.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit/string_extension.rb",
     "spec/support/vendor/screw-unit/lib/screw_unit.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/array_extension_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/asset_location_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/asset_manager_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/configuration_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/dispatcher_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/js_file_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/dir_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/file_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/root_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/spec_dir_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/spec_suite_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/resources/suite_completion_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit/server_spec.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit_spec_helper.rb",
     "spec/support/vendor/screw-unit/spec/screw_unit_spec_suite.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

