# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coolerator.vision}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Innis"]
  s.date = %q{2009-11-10}
  s.description = %q{A Rails plugin}
  s.email = %q{corey@coolerator.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/placeholder.txt",
     "app/placeholder.txt",
     "coolerator.vision.gemspec",
     "lib/coolerator.vision.rb",
     "public/javascripts/vendor/coolerator/coolerator.base.js",
     "public/javascripts/vendor/coolerator/coolerator.base.js",
     "public/javascripts/vendor/coolerator/coolerator.filter.js",
     "public/javascripts/vendor/coolerator/coolerator.filter.js",
     "public/javascripts/vendor/coolerator/coolerator.module.js",
     "public/javascripts/vendor/coolerator/coolerator.module.js",
     "public/javascripts/vendor/coolerator/coolerator.registrar.js",
     "public/javascripts/vendor/coolerator/coolerator.registrar.js",
     "public/javascripts/vendor/coolerator/coolerator.remote.js",
     "public/javascripts/vendor/coolerator/coolerator.remote.js",
     "public/javascripts/vendor/coolerator/coolerator.view.js",
     "public/javascripts/vendor/coolerator/coolerator.view.js",
     "public/javascripts/vendor/jquery/jquery.easing.js",
     "public/javascripts/vendor/jquery/jquery.easing.js",
     "public/javascripts/vendor/jquery/jquery.js",
     "public/javascripts/vendor/jquery/jquery.js",
     "public/javascripts/vendor/prez/prez.js",
     "public/javascripts/vendor/prez/prez.js",
     "rails/init.rb",
     "spec/coolerator.vision_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/coreyti/coolerator.vision}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails plugin}
  s.test_files = [
    "spec/coolerator.vision_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

